import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import NavbarGlobal from "../components/Navbar.js"

import { Grid, Container } from "@nextui-org/react";
import { Card1 } from '../components/Card1';
import { Card2 } from '../components/Card2';
import { Card3 } from '../components/Card3';
import { Card4 } from '../components/Card4';
import { Card5 } from '../components/Card5';

export default function Home() {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <NavbarGlobal />

      <Container>
        <h1 className={styles.titletext}>Angus Cronin-Guss</h1>
        <h3 className={styles.biotext}>Full Stack Web Developer based out of Melbourne, Australia</h3>
        <h3 className={styles.biotext}><strong className="specialties-span">Specialties</strong>:&nbsp; React.JS, Node.JS, SQL, Next.JS, JavaScript & Ruby</h3>
      </Container>
      <Container>
        <Grid.Container gap={2} justify="center">
          <Grid xs={12} sm={4}>
            <Card1 />
          </Grid>
          <Grid xs={12} sm={4}>
            <Card2 />
          </Grid>
          <Grid xs={12} sm={4}>
            <Card3 />
          </Grid>
          <Grid xs={12} sm={5}>
            <Card4 />
          </Grid>
          <Grid xs={12} sm={7}>
            <Card5 />
          </Grid>
        </Grid.Container>
      </Container>


    </div>
  )
}


